// UIcomponents/LTR/UIcomponents/LTR/banners/BannerCentredWithLink.vue
<template>
  <div class="bg-indigo-600">
    <div class="max-w-screen-xl mx-auto px-4 py-3 items-center gap-x-4 justify-center text-white sm:flex md:px-8">
      <p class="py-2 font-medium">
        We just launched our new product! you can check out all features now.
      </p>
      <a href="javascript:void(0)" class="flex-none inline-block w-full mt-3 py-2 px-3 text-center text-indigo-600 font-medium bg-white duration-150 hover:bg-gray-100 active:bg-gray-200 rounded-lg sm:w-auto sm:mt-0 sm:text-sm">
        Learn more
      </a>
    </div>
  </div>
</template>

// UIcomponents/LTR/banners/BannerCentredWithLink.jsx
export default () => {
    return (
        <div className="bg-indigo-600">
            <div className="max-w-screen-xl mx-auto px-4 py-3 items-center gap-x-4 justify-center text-white sm:flex md:px-8">
                <p className="py-2 font-medium">
                    We just launched our new product! you can check out all features now.
                </p>
                <a href="javascript:void(0)" className="flex-none inline-block w-full mt-3 py-2 px-3 text-center text-indigo-600 font-medium bg-white duration-150 hover:bg-gray-100 active:bg-gray-200 rounded-lg sm:w-auto sm:mt-0 sm:text-sm">
                    Learn more
                </a>
            </div>
        </div>
    )
}
