// UIcomponents/RTL/banners/banner-centred.jsx
export default () => {
    return (
        <div className="bg-indigo-600">
            <div className="max-w-screen-xl mx-auto px-4 py-3 text-white sm:text-center md:px-8">
                <p className="font-medium">
                    لقد أطلقنا للتو نسخة جديدة من مكتبتنا! <a href="javascript:(0)" className="font-semibold underline duration-150 hover:text-indigo-100 inline-flex items-center gap-x-1">
                        معرفة المزيد
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-5 h-5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18" />
                        </svg>
                    </a>
                </p>
            </div>
        </div>
    )
}

// UIcomponents/RTL/banners/BannerCentred.vue
<template>
  <div class="bg-indigo-600">
    <div class="max-w-screen-xl mx-auto px-4 py-3 text-white sm:text-center md:px-8">
      <p class="font-medium">
        لقد أطلقنا للتو نسخة جديدة من مكتبتنا!  <a href="javascript:(0)" class="font-semibold underline duration-150 hover:text-indigo-100 inline-flex items-center gap-x-1">
        معرفة المزيد
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
          <path fill-rule="evenodd" d="M5 10a.75.75 0 01.75-.75h6.638L10.23 7.29a.75.75 0 111.04-1.08l3.5 3.25a.75.75 0 010 1.08l-3.5 3.25a.75.75 0 11-1.04-1.08l2.158-1.96H5.75A.75.75 0 015 10z"
                clip-rule="evenodd"/>
        </svg>
      </a>
      </p>
    </div>
  </div>
</template>
